### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/Html#1]
Per le intestazioni esistono tag fatti apposta. Strong non va bene

Poi veniva chiesta una lista di collegamenti

**Comment by Billie99** [comment]
Ho corretto! Prof scasate ma il tag strong ho letto che viene usato per un titolo importante! E non va bene in quel caso?

**Comment by FabioZTessitore** [comment]
Non per un titolo, ma per mettere in evidenza forte

**Comment by FabioZTessitore** [comment]
va bene, cmq in `li` non è necessario mettere `p`
