### ISSUE TITLE
Sport

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/Html#4]
Aggiusta le intestazioni, la tebella, tutto

**Comment by Billie99** [comment]
Le tabelle non vanno bene?

**Comment by Billie99** [comment]
Prof ho corretto vedete se vanno bene le tabelle!

**Comment by FabioZTessitore** [comment]
togli tutti i `<center>`, i `<b>`

poi togli quei finti bordi alla tabella

**Comment by Billie99** [comment]
Prof scusate ma il tag center non si usa? L'anno scorso ce lo facevano usare sempre

**Comment by FabioZTessitore** [comment]
L'anno scorso lo devi cancellare.
Puoi usare i tag che danno significato (intestazione, paragrafo, lista,
ecc.), non quelli che dicono come visualizzare gli elementi

Il 16 feb 2017 4:13 PM, "Billie99" <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
ho messo dei suggerimenti nel codice, fai un pull

**Comment by Billie99** [comment]
Va bene

**Comment by Billie99** [comment]
Prof ho corretto tutto! Vedete se va bene
